### ISSUE TITLE
Merge with Cobalt2 main?

### ISSUE THREAD

**Issue by wesbos** [robertoachar/vscode-theme-cobalt2#1]
Hey - just found this repo - it's amazing because I don't have a theme for Cobalt2 yet. 

Do you want to merge this with my own repo so everyone can install it when they install the colour scheme?

github.com/wesbos/cobalt2

**Comment by robertoachar** [comment]
Hey Wes,

Absolutely, it'll be my pleasure. When I first developed it, I tought about showing it to you, but I tought that'd be a little out of my league. I'm very glad you reached out! 

How do you want to do this?

**Comment by wesbos** [comment]
Awesome - I appreciate the work you put into it! I've just forked it to make some smaller changes. 

I think I might split the SUblime theme and the VS code theme into two different repos - will report back!

**Comment by wesbos** [comment]
Okay I've got everything over here now:

https://github.com/wesbos/cobalt2-vscode

I've kept all your commits in place :) 

Do you know if it's possible to merge a theme? Or tell people using this one to swithc?

**Comment by robertoachar** [comment]
I don't think there is a way to merge the themes.

I think the best option is to say that the theme is obsolete and put the official link to your theme. I can do that now. Send me how you would like me to do this.

I can also see with Microsoft if there is a way to unpublish my theme.

I need to say that. Believe it or not, my father is my best friend. Some time ago I talked to him about you, the things you do, the bright person you are. And I told him, this guy inspires me every day and someday I might be able to help him with something. And that day has come. When I showed my father what I had done, he was very proud of me. Wes, it's just a theme, but it meant a lot to me. Thank you, really!

**Comment by robertoachar** [comment]
So I just found this:
https://code.visualstudio.com/docs/extensions/publish-extension

![unpublish-extension](https://user-images.githubusercontent.com/7755073/30394790-8bc344aa-989a-11e7-8131-e6de9bc057bd.png)

**Comment by wesbos** [comment]
:D Well you are welcome - thank you for the work on the them - saved me many hours! You are awesome. 

I wonder if you unpublish the extension, if it will remove it from people's VS code or not. I think maybe the best way is to deprecate it and hope people see the notice. 

Maybe just link to this: https://marketplace.visualstudio.com/items?itemName=wesbos.theme-cobalt2

**Comment by robertoachar** [comment]
I just made the changes for you!

https://github.com/robertoachar/vscode-theme-cobalt2/blob/deprecated/README.md

Sounds good to you?

**Comment by robertoachar** [comment]
![Deprecated](https://user-images.githubusercontent.com/7755073/30491582-12a747c6-9a14-11e7-91b6-8b236476d92a.png)

**Comment by wesbos** [comment]
Sweet thanks a lot - can you change it to [DEPRECATED] Cobalt2 - sometimes the end of a theme is cut off in the sidebar
